-- bootstrap_schema.sql already contains the schema produced by migrations 001-054.
-- Record that baseline on a brand-new database so the application role does not
-- replay historical DDL after ownership and least-privilege rules are applied.

INSERT INTO public.migration_history (migration_name, success)
VALUES
    ('001_add_destination_manager_name.sql', TRUE),
    ('002_add_visitor_tags.sql', TRUE),
    ('003_extend_audit_log.sql', TRUE),
    ('004_create_missing_tables.sql', TRUE),
    ('005_add_shift_reports.sql', TRUE),
    ('006_add_report_file_path.sql', TRUE),
    ('007_create_fire_alarms.sql', TRUE),
    ('008_add_alarm_number.sql', TRUE),
    ('009_make_visitor_fields_optional.sql', TRUE),
    ('010_update_managers_list.sql', TRUE),
    ('011_add_whatsapp_notification.sql', TRUE),
    ('012_create_sgk_records.sql', TRUE),
    ('013_add_personnel_names_to_all_tables.sql', TRUE),
    ('014_separate_given_and_returned_personnel.sql', TRUE),
    ('015_create_personnel_records_and_equipment_checks.sql', TRUE),
    ('016_set_turkey_timezone.sql', TRUE),
    ('017_add_passport_to_sgk.sql', TRUE),
    ('018_fix_sgk_hashed_tc_nullable.sql', TRUE),
    ('019_create_incident_categories.sql', TRUE),
    ('020_relax_sgk_identifier_check.sql', TRUE),
    ('021_create_sgk_record_files.sql', TRUE),
    ('022_add_children_count_to_visitor_records.sql', TRUE),
    ('023_add_gate_to_records.sql', TRUE),
    ('024_create_misafir_kayitlari.sql', TRUE),
    ('025_align_misafir_kayitlari_excel_columns.sql', TRUE),
    ('026_convert_guest_date_time_columns.sql', TRUE),
    ('027_create_gate_equipment_config.sql', TRUE),
    ('028_create_system_settings.sql', TRUE),
    ('029_personnel_username_partial_unique.sql', TRUE),
    ('030_make_gate_constraints_dynamic.sql', TRUE),
    ('031_add_weekly_login_counter_to_personnel.sql', TRUE),
    ('032_add_daily_guest_to_visitor_records.sql', TRUE),
    ('033_add_entry_exit_tags_to_visitor_records.sql', TRUE),
    ('034_add_highlight_color_to_visitor_records.sql', TRUE),
    ('035_add_tour_and_guide_tags.sql', TRUE),
    ('036a_add_gate_to_incidents.sql', TRUE),
    ('036b_add_meeting_and_delivery_tags_to_visitor_records.sql', TRUE),
    ('037_relax_incidents_gate_constraint.sql', TRUE),
    ('038_add_composite_indexes.sql', TRUE),
    ('039_create_pending_qr_visitors.sql', TRUE),
    ('040_create_pending_qr_sgk.sql', TRUE),
    ('041_create_predefined_visitors.sql', TRUE),
    ('042_add_highlight_color_to_predefined_visitors.sql', TRUE),
    ('043_add_gate_to_pending_qr_sgk.sql', TRUE),
    ('044_add_visitor_records_name_tr_index.sql', TRUE),
    ('045_drop_predefined_visitors.sql', TRUE),
    ('046_harden_vehicle_records.sql', TRUE),
    ('047_vehicle_plate_active_unique.sql', TRUE),
    ('048_harden_visitor_records.sql', TRUE),
    ('049_harden_manager_records.sql', TRUE),
    ('050_harden_guest_registry.sql', TRUE),
    ('051_optimize_fire_alarm_records.sql', TRUE),
    ('052_harden_incident_records.sql', TRUE),
    ('053_harden_sgk_records.sql', TRUE),
    ('054_enforce_record_chronology.sql', TRUE)
ON CONFLICT (migration_name) DO UPDATE
SET success = EXCLUDED.success;
